/*
 * action types
 */

export const FETCH_TRACKS_START = "FETCH_TRACKS_START";
export const FETCH_TRACKS_SUCCESS = "FETCH_TRACKS_SUCCESS";
export const FETCH_TRACKS_FAILURE = "FETCH_TRACKS_FAILURE";

export const SESSION_PLAY_TRACK = "SESSION_PLAY_TRACK";
export const SESSION_PLAYING_TOGGLE = "SESSION_PLAYING_TOGGLE";
export const SESSION_PLAYING_UPDATE_STATUS = "SESSION_PLAYING_UPDATE_STATUS";
export const SESSION_VOLUME = "SESSION_VOLUME";

export const UPDATE_USER_SEARCH = "UPDATE_USER_SEARCH";
export const FILTER_TOGGLE_TAG = "FILTER_TOGGLE_TAG";
